### ISSUE TITLE
At Step-5,Cannot marshall 'class org.infinispan.tutorial.embedded.LocationWeather'

### ISSUE THREAD

**Issue by kawakamimanabu** [infinispan/infinispan-embedded-tutorial#11]
At Step-5, after 2nd terminal is started, the WeatherApp raised exceptions as follows.

WARN: ISPN000559: Cannot marshall 'class org.infinispan.tutorial.embedded.LocationWeather'
java.lang.IllegalArgumentException: No marshaller registered for Java type org.infinispan.tutorial.embedded.LocationWeather
        at org.infinispan.protostream.impl.SerializationContextImpl.getMarshallerDelegate(SerializationContextImpl.java:279)
        at org.infinispan.protostream.WrappedMessage.writeMessage(WrappedMessage.java:240)
        at org.infinispan.protostream.ProtobufUtil.toWrappedStream(ProtobufUtil.java:196)
...

I guess "GlobalConfigurationBuilder" needs more configuration.

**Comment by kawakamimanabu** [comment]
Please check the update.

https://github.com/infinispan/infinispan-embedded-tutorial/compare/step-5...kawakamimanabu:add_serialization_marshaller_step_5?expand=1

**Comment by ryanemerson** [comment]
@kawakamimanabu Thanks for the PR! However, the tutorial should really use ProtoStream based marshalling as that is [default](https://infinispan.org/docs/stable/titles/developing/developing.html#protostream_cm_config) (and recommended) marshalling to use. I will create a new PR shortly to fix this.

**Comment by kawakamimanabu** [comment]
Thank you very much! Can I close this?

**Comment by ryanemerson** [comment]
I'll close once the PR is up and merged. Thanks :+1:

**Comment by kawakamimanabu** [comment]
Ok.thx

**Comment by karesti** [comment]
we are upgrading the tutorial @kawakamimanabu 
thanks for reporting
