### ISSUE TITLE
Tags are not present in github repository

### ISSUE THREAD

**Issue by connormclaud** [infinispan/infinispan-embedded-tutorial#3]
There are no tags in this repository so examples from tutorial which refer to tags don't work.

Git don't push tags on remote by default.

In order to fix this you can do the following

`$ git push --tags`

To check whether it is fixed you can check that
`$ git log --tags --decorate=full`
shows tags in newly cloned repository

**Comment by tristantarrant** [comment]
Sorry they got removed during the latest round of changes. Thanks for noticing
