### ISSUE TITLE
After enabling clustering cache initialization is too slow

### ISSUE THREAD

**Issue by connormclaud** [infinispan/infinispan-embedded-tutorial#4]
I'm using Ubuntu Linux 16.04.

After steps described in step-5 I've got following warnings in my console:

> May 30, 2016 2:03:29 PM org.jgroups.protocols.UDP setBufferSize
> WARNING: JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. net.core.wmem_max on Linux)
> May 30, 2016 2:03:29 PM org.jgroups.protocols.UDP setBufferSize
> WARNING: JGRP000015: the receive buffer of socket MulticastSocket was set to 20MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max receive buffer in the OS correctly (e.g. net.core.rmem_max on Linux)
> May 30, 2016 2:03:29 PM org.jgroups.protocols.UDP setBufferSize
> WARNING: JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. net.core.wmem_max on Linux)
> May 30, 2016 2:03:29 PM org.jgroups.protocols.UDP setBufferSize
> WARNING: JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max receive buffer in the OS correctly (e.g. net.core.rmem_max on Linux)

And cache initialization takes much time (around 10 seconds on average).
When running two instances cache lookup is also very slow (about 3 seconds vs 1s on not cached version).

**Comment by connormclaud** [comment]
Tweaking sysctrl removes warning messages but doesn't resolve performance issues. Distributed cache is incredibly slow.

**Comment by connormclaud** [comment]
I've just realized that I probably want too much performance from distributed cache written in Java.
I've checked my project and performance is adequate over distributed cluster with dozen of clients.

**Comment by wburns** [comment]
The 10s startup is probably due to your discovery protocol timing out since it can't find any members.  This is VERY important to prevent split brain right off the bat.  If you wanted to reduce that you could decrease the discovery timeout [1].

In regards to a 2 node distributed cache it makes no sense that it would be 3s since all values would be in each node.  It sounds like there is something else going on.  This should be almost the same performance as just a regular concurrent hash map.

[1] http://jgroups.org/manual/index.html#Discovery

**Comment by tristantarrant** [comment]
Running the demo against the real openweathermap API I get 
Fetched in 1583ms
The second pass (cached) is:
Fetched in 2ms
These numbers obviously come from a cold JVM, where the number of iterations is not enough for HotSpot to kick in.
Cluster formation has a default join_timeout of 5000ms to prevent the split brains Will describes above.
