### ISSUE TITLE
Exception in threadException in thread

### ISSUE THREAD

**Issue by precious21** [infinispan/infinispan-embedded-tutorial#5]
org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheConfigurationException: ISPN000085: Error while trying to create a channel using the specified configuration file: default-configs/default-jgroups-udp.xml

**Comment by precious21** [comment]
how can i solved this please any one guide me i imported this orject

**Comment by tristantarrant** [comment]
Any more logs ?

**Comment by tristantarrant** [comment]
Closing this as out-of-date
