### ISSUE TITLE
no steps?

### ISSUE THREAD

**Issue by danteorlando** [infinispan/infinispan-embedded-tutorial#8]
Does this tutorial still work? There don't appear to be any tags corresponding to the steps.

$ git checkout step-0
error: pathspec 'step-0' did not match any file(s) known to git.

If I try to build and run the app as is I don't get any output just a rolling set of log messages....

**Comment by tristantarrant** [comment]
We forgot to re-run the tutorial tagger script after some updates. I'll fix it and verify that everything still works

**Comment by tristantarrant** [comment]
Ok, done.

**Comment by danteorlando** [comment]
Perfect, thank you!
